### ISSUE TITLE
Script not calling gtmOnSuccess

### ISSUE THREAD

**Issue by philpott** [mopinion/mopinion-gtm-template#1]
https://github.com/mopinion/mopinion-gtm-template/blob/61fa2ac5d8f0ebf4b65a1795cd957a2f2364fc33/template.tpl#L69

Your script does not call data.gtmOnSuccess -- it's commented out. Please fix the script and respond to this bug and we'll re-review the tag.

**Comment by GustaafL** [comment]
Hi Phil,

Thank you for reviewing. I've removed the commented line. Let me know if there are any other notes.

**Comment by philpott** [comment]
Template's require data.gtmOnSuccess to have been called to know when the tag/variable have completed execution. To fix this you need to add the data.gtmOnSuccess() call back as the last line inside of your onSuccess function.

Thanks
Michael

**Comment by GustaafL** [comment]
Hi Michael,

I've added the data.gtmOnSuccess() call back to the onSuccess function again. Sorry about misunderstanding this earlier.

**Comment by philpott** [comment]
Thanks for making the change!
